name: Container Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo 
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Repository
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Source Version Environment File
      run: |
        while read p; do
          echo "$p" >> $GITHUB_ENV
        done <${{ inputs.image_name }}/versions

    - name: Build and push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v2
      with:
        context: ./${{ inputs.image_name }}
        # push: true
        tags: |
          ghcr.io/base2services/${{ inputs.image_name }}:latest
          ghcr.io/base2services/${{ inputs.image_name }}:${{ env.image_version }}
        labels: |
          runnumber=${GITHUB_RUN_ID}
          org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}
        build-args: ${{ env.build_args }}